name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update known hosts
        run: |
          echo "$HOST_KEY" >> ~/.ssh/known_hosts

      - name: Debug SSH connection
        run: |
          ssh-keyscan ec2-43-204-130-236.ap-south-1.compute.amazonaws.com >> known_hosts
          cat keyfile
          cat ~/.ssh/known_hosts

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          ssh -t -i keyfile ubuntu@ec2-43-204-130-236.ap-south-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
